Import('*')

SimObject('SimpleDeviceObj.py', sim_objects=['SimpleDeviceObj'])

Source('simple_deviceobj.cc')

DebugFlag('Device_Obj', "Print out Device_Obj debug messages")
DebugFlag('Device_Obj_begin')
